[build]
  publish = "public"      # บอก Netlify ว่าไฟล์เว็บของคุณอยู่ในโฟลเดอร์ 'public'
  functions = "netlify/functions" # บอก Netlify ว่า Functions ของคุณอยู่ในโฟลเดอร์ 'netlify/functions'

[functions]
  node_bundler = "esbuild"
  node_version = "18" # แนะนำ Node.js 18 ขึ้นไป